// Generated by IcedCoffeeScript 108.0.9
(function() {
  var page, rand, system;

  page = require('webpage').create();

  system = require('system');

  rand = function() {
    return Math.floor(Math.random() * 5000);
  };

  setTimeout((function() {
    console.log("UNEXPECTED ERROR, TIMEOUT, HALT!");
    return phantom.exit();
  }), 600000);

  page.open(system.args[1], function(status) {
    if (status === "success") {
      console.log(Date() + " start video");
      return setTimeout((function() {
        console.log(Date() + " end video");
        return phantom.exit();
      }), 540000 + rand());
    } else {
      console.log("error on connection " + status + " HALT");
      return phantom.exit();
    }
  });

}).call(this);
