// Generated by IcedCoffeeScript 108.0.9
(function() {
  var mmove, page, rand, system;

  page = require('webpage').create();

  system = require('system');

  rand = function() {
    return Math.floor(Math.random() * 60000);
  };

  mmove = function() {
    page.sendEvent('mousemove', rand(), rand());
    return setTimeout(mmove, Math.floor(rand() / 100));
  };

  setTimeout((function() {
    console.log("UNEXPECTED ERROR, TIMEOUT, HALT!");
    return slimer.exit();
  }), 600000 + rand());

  page.open(system.args[1], function(status) {
    if (status === "success") {
      console.log(Date() + " start video");
      mmove();
      return setTimeout((function() {
        console.log(Date() + " end video");
        return slimer.exit();
      }), 600000 + rand());
    } else {
      console.log("error on connection " + status + " HALT");
      return slimer.exit();
    }
  });

}).call(this);
